stages: [plan, apply]

image: hashicorp/terraform:1.6.6

variables:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

before_script:
  - apk add --no-cache bash curl jq git
  # If you've committed the executable bit (see note at bottom), remove this:
  - chmod +x ./check-group.sh
  # Generate the .auto.tfvars file (no -var flags needed later)
  - ./check-group.sh "chris/devops/automation/terraform" "frontoend-moduels" --emit-tfvars

plan:
  stage: plan
  script:
    - terraform init
    - terraform plan
  artifacts:
    when: always
    paths:
      - .terraform
      - .terraform.lock.hcl
    expire_in: 1 week

apply:
  stage: apply
  when: manual
  script:
    - terraform init
    - terraform apply -auto-approve
